version: "3"
services:
  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    #    extra_hosts:
    #      - "host.docker.internal:host-gateway"
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./:${WORKDIR}
    links:
      - db_mysql

  nginx:
    container_name: nginx_${PROJECT_NAME}
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./:${WORKDIR}
    depends_on:
      - php

  db_mysql:
    container_name: mysql_${PROJECT_NAME}
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      WORKDIR: ${WORKDIR}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-hillel_task7}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - ./docker/databases/mysql_dump:/docker-entrypoint-initdb.d